name: Trivia - Create release

env:
  CI: true
  ISOLATE: true
  GIT_DEPTH: 0
  BABEL_DISABLE_CACHE: '1'
  NODE_ENV: 'production'

on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    name: Create releases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: c-hive/gha-yarn-cache@v1
      - name: Install dependencies
        run: yarn install
      - name: Create frontend release
        run: |
          yarn frontend build
          tar cfj /tmp/frontend.tar.bz2 -C packages/web-frontend/build .
      - name: Publish release
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: false
          title: 'Latest build'
          files: |
            /tmp/frontend.tar.bz2
